name: Build and push docker image

on: [push]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/hawk-yard

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}
